// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbGA0lS_XiK4BUEuFQXvUzRs2Nm_xkyn8',
    appId: '1:964561318957:web:44a72240bad0d19562b4a4',
    messagingSenderId: '964561318957',
    projectId: 'deliveryapp-99e7f',
    authDomain: 'deliveryapp-99e7f.firebaseapp.com',
    databaseURL: 'https://deliveryapp-99e7f-default-rtdb.firebaseio.com',
    storageBucket: 'deliveryapp-99e7f.firebasestorage.app',
    measurementId: 'G-VC23C5K57Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtPbqxDRSmb3P5Bj5NK9OVmniDmdOmm3Q',
    appId: '1:964561318957:android:cd1d85e1b21d6b2d62b4a4',
    messagingSenderId: '964561318957',
    projectId: 'deliveryapp-99e7f',
    databaseURL: 'https://deliveryapp-99e7f-default-rtdb.firebaseio.com',
    storageBucket: 'deliveryapp-99e7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZx-OVqm5C68Ab-vHGvg2bP16qzwJTI7c',
    appId: '1:964561318957:ios:6beb8b2015e7a27262b4a4',
    messagingSenderId: '964561318957',
    projectId: 'deliveryapp-99e7f',
    databaseURL: 'https://deliveryapp-99e7f-default-rtdb.firebaseio.com',
    storageBucket: 'deliveryapp-99e7f.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
